package com.flight.trs.model.entity;
// Generated 2016-1-16 17:01:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.flight.trs.model.IDeleteNotPhysically;

/**
 * CityAirport generated by hbm2java
 */
@Entity
@Table(name = "TRS_AIRPORT")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@JsonAutoDetect(fieldVisibility=JsonAutoDetect.Visibility.ANY)
@JsonIgnoreProperties({"serialVersionUID","distInterStrings","isDeleted"})
public class Airport implements java.io.Serializable 
	, IDeleteNotPhysically{

	private static final long serialVersionUID = 2862670626073871638L;
	private String code;		//机场三字码
	private String cityName;	//城市名称
	private String cityNameInitial;//城市首字母
	private String airportName;		//机场名称
	private String dist;			//所属区域（国内）或大洲（港澳台、国际）
	private char isHot = 'n';		//是否为热门
	private char isDeleted = 'n';	//是否被删除
	
	//getter、setter
	
	private static String[] distInterStrings = {"Asia","America","Europe","Africa","Oceania"};
	public Airport() {
	}

	public Airport(String code, String cityName, String airportName) {
		this.code = code;
		this.cityName = cityName;
		this.airportName = airportName;
	}

	public Airport(String code, String cityName, String cityNameInitial, String airportName
			, String dist, char isHot) {
		this.code = code;
		this.cityName = cityName;
		this.cityNameInitial = cityNameInitial;
		this.airportName = airportName;
		this.dist = dist;
		this.isHot = isHot;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CITY_NAME", nullable = false, length = 20)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "CITY_NAME_INITIAL", nullable = false, length = 1)
	public String getCityNameInitial() {
		return cityNameInitial;
	}

	public void setCityNameInitial(String cityNameInitial) {
		this.cityNameInitial = cityNameInitial;
	}
	
	@Column(name = "AIRPORT_NAME", nullable = false, length = 24)
	public String getAirportName() {
		return this.airportName;
	}

	public void setAirportName(String airportName) {
		this.airportName = airportName;
	}
	
	@Column(name = "DIST", nullable = true, length = 20)
	public String getDist() {
		return dist;
	}

	public void setDist(String dist) {
		this.dist = dist;
	}

	@Column(name = "IS_HOT", nullable = false, length = 1)
	public char getIsHot() {
		return isHot;
	}

	public void setIsHot(char isHot) {
		this.isHot = isHot;
	}
	
	@Column(name = "IS_DELETED", nullable = false, length = 1)
	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

	//判断是否为热门机场
	@Transient
	@JsonIgnore
	public boolean isDeleted(){
		return getIsDeleted() == 'y';
	}
	
	//判断是否为热门机场
	@Transient
	@JsonIgnore
	public boolean isHot(){
		return isHot == 'y';
	}
	
	//判断是否为国际机场(否则为国内机场)
	@Transient
	@JsonIgnore
	public boolean isInternational(){
		for (String distInterString : distInterStrings) {
			if (getDist()!=null && getDist().equals(distInterString)) {
				return true;
			}
		}
		return false;
	}
	
	@Transient
	@Override
	public void deleteNotPhysically() {
		// TODO
		setIsDeleted('y');
	}
}
