package com.flight.trs.model.entity;
// Generated 2016-1-16 17:01:14 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.flight.trs.model.IDeleteNotPhysically;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "TRS_EMPLOYEE")
@JsonAutoDetect(fieldVisibility=JsonAutoDetect.Visibility.ANY)
@JsonIgnoreProperties({"serialVersionUID","password","isDeleted"})
public class Employee implements java.io.Serializable 
	, IDeleteNotPhysically{

	/** 
	 * @Fields serialVersionUID : TODO
	 */ 
	private static final long serialVersionUID = -7331609422470306541L;
	private int no;					//员工工号
	private String role;			//员工角色
	private String password;		//登录密码
	private String staticSalt;		//静态随机盐
	private String dynamicSalt;     //动态随机盐
	private char isLocked = 'u';	//是否已被
	private char isDeleted = 'n';	//是否已被删除
	private List<Order> ordersToHandle = new ArrayList<Order>(0);	//该员工经手的订单
	
	public Employee() {
	}

	public Employee(String role, String password, String staticSalt, String dynamicSalt) {
		this.role = role;
		this.password = password;
		this.staticSalt = staticSalt;
		this.dynamicSalt = dynamicSalt;
	}

	@Id
	@GeneratedValue(generator = "seqGeneratorEMPLOYEE")
	@SequenceGenerator(name = "seqGeneratorEMPLOYEE"
		, sequenceName = "SEQ_EMPLOYEE"
		, allocationSize=1
		)
	@Column(name = "NO", insertable = false, updatable = false
		, unique = true, nullable = false, precision = 8, scale = 0
		)
	public int getNo() {
		return this.no;
	}
	
	public void setNo(int no) {
		this.no = no;
	}

	@Column(name = "ROLE", nullable = false, length = 18)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "PASSWORD", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "STATIC_SALT")
	public String getStaticSalt() {
		return staticSalt;
	}
	
	public void setStaticSalt(String staticSalt) {
		this.staticSalt = staticSalt;
	}
	
	@Column(name = "DYNAMIC_SALT")
	public String getDynamicSalt() {
		return dynamicSalt;
	}
	
	public void setDynamicSalt(String dynamicSalt) {
		this.dynamicSalt = dynamicSalt;
	}
	
	@Column(name = "IS_LOCKED", nullable = false, length = 1)
	public char getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(char isLocked) {
		this.isLocked = isLocked;
	}

	@Column(name = "IS_DELETED", nullable = false, length = 1)
	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "handler")
	@OrderBy("orderDate desc")
	public List<Order> getOrdersToHandle() {
		return ordersToHandle;
	}

	public void setOrdersToHandle(List<Order> ordersToHandle) {
		this.ordersToHandle = ordersToHandle;
	}
	
	@Transient
	@Override
	public void deleteNotPhysically() {
		// TODO
		setIsDeleted('y');
	}


}
