package com.flight.trs.model.entity;
// Generated 2016-1-16 17:01:14 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.flight.trs.model.IDeleteNotPhysically;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "TRS_PAYMENT")
@JsonAutoDetect(fieldVisibility=JsonAutoDetect.Visibility.ANY)
@JsonIgnoreProperties({"serialVersionUID","isDeleted"})
public class Payment implements java.io.Serializable 
	, IDeleteNotPhysically{

	/** 
	 * @Fields serialVersionUID : TODO
	 */ 
	private static final long serialVersionUID = -2343833382159094682L;
	private BigDecimal id;
	private Order order;
	private String paymentMode;
	private String paymentAccount;
	private double amount;
	private String transSeqNo;
	private Date paymentTime;
	private char isDeleted = 'n';

	public Payment() {
	}

	public Payment(Order order, String paymentMode, String paymentAccount, String transSeqNo,
			double amount,Date paymentTime) {
		this.order = order;
		this.paymentMode = paymentMode;
		this.paymentAccount = paymentAccount;
		this.amount = amount;
		this.transSeqNo = transSeqNo;
		this.paymentTime = paymentTime;
	}

	@Id
	@SequenceGenerator(name = "seqGeneratorPAYMENT"
		, sequenceName = "SEQ_PAYMENT"
		, allocationSize=1
		)
	@GeneratedValue(generator = "seqGeneratorPAYMENT")
	@Column(name = "ID", insertable = false, updatable = false, unique = true
		, nullable = false, precision = 20, scale = 0
		)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_NO", nullable = false)
	@JsonIgnore
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "PAYMENT_MODE", nullable = false, length = 24)
	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	@Column(name = "PAYMENT_ACCOUNT", nullable = false, length = 32)
	public String getPaymentAccount() {
		return this.paymentAccount;
	}

	public void setPaymentAccount(String paymentAccount) {
		this.paymentAccount = paymentAccount;
	}
	
	@Column(name = "AMOUNT", nullable = false, precision = 12, scale = 2)
	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}
	
	@Column(name = "TRANS_SEQ_NO", length = 20)
	public String getTransSeqNo() {
		return this.transSeqNo;
	}

	public void setTransSeqNo(String transSeqNo) {
		this.transSeqNo = transSeqNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PAYMENT_TIME", nullable = false)
	public Date getPaymentTime() {
		return this.paymentTime;
	}

	public void setPaymentTime(Date paymentTime) {
		this.paymentTime = paymentTime;
	}
	
	@Column(name = "IS_DELETED", nullable = false, length = 1)
	@JsonIgnore
	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Transient
	@Override
	public void deleteNotPhysically() {
		// TODO
		setIsDeleted('y');
	}
}
