package com.flight.trs.model.entity;
//Generated 2016-1-16 17:01:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
* PassengerGaugeId generated by hbm2java
*/
@Embeddable
@JsonAutoDetect(fieldVisibility=JsonAutoDetect.Visibility.ANY)
@JsonIgnoreProperties("serialVersionUID")
public class SegmentId implements java.io.Serializable {

	/** 
	 * @Fields serialVersionUID : TODO
	 */ 
	private static final long serialVersionUID = -9024642868635588951L;
	
	@Column(name = "CARRIER_CODE", nullable = false, length = 2)
	private String carrierCode;
	
	@Column(name = "FLIGHT_NO", nullable = false, length = 4)
	private String flightNo;

	@Column(name = "DEP_AIRPORT_CODE", nullable = false, length = 3)
	private String depAirportCode;
	
	@Column(name = "ARR_AIRPORT_CODE", nullable = false, length = 3)
	private String arrAirportCode;
	
	@Column(name = "DEP_TIME", nullable = false, length = 4)
	private String depTime;
	
	public SegmentId() {
	}

	public SegmentId(String carrierCode, String flightNo, String depAirportCode, String arrAirportCode,
			String depTime) {
		super();
		this.carrierCode = carrierCode;
		this.flightNo = flightNo;
		this.depAirportCode = depAirportCode;
		this.arrAirportCode = arrAirportCode;
		this.depTime = depTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((arrAirportCode == null) ? 0 : arrAirportCode.hashCode());
		result = prime * result + ((carrierCode == null) ? 0 : carrierCode.hashCode());
		result = prime * result + ((depAirportCode == null) ? 0 : depAirportCode.hashCode());
		result = prime * result + ((depTime == null) ? 0 : depTime.hashCode());
		result = prime * result + ((flightNo == null) ? 0 : flightNo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SegmentId other = (SegmentId) obj;
		if (arrAirportCode == null) {
			if (other.arrAirportCode != null)
				return false;
		} else if (!arrAirportCode.equals(other.arrAirportCode))
			return false;
		if (carrierCode == null) {
			if (other.carrierCode != null)
				return false;
		} else if (!carrierCode.equals(other.carrierCode))
			return false;
		if (depAirportCode == null) {
			if (other.depAirportCode != null)
				return false;
		} else if (!depAirportCode.equals(other.depAirportCode))
			return false;
		if (depTime == null) {
			if (other.depTime != null)
				return false;
		} else if (!depTime.equals(other.depTime))
			return false;
		if (flightNo == null) {
			if (other.flightNo != null)
				return false;
		} else if (!flightNo.equals(other.flightNo))
			return false;
		return true;
	}

	public String getCarrierCode() {
		return carrierCode;
	}

	public void setCarrierCode(String carrierCode) {
		this.carrierCode = carrierCode;
	}

	public String getFlightNo() {
		return flightNo;
	}

	public void setFlightNo(String flightNo) {
		this.flightNo = flightNo;
	}

	@Transient
	public String getTotalFlightNo(){
		return this.carrierCode + this.flightNo;
	}
	
	public String getDepAirportCode() {
		return depAirportCode;
	}

	public void setDepAirportCode(String depAirportCode) {
		this.depAirportCode = depAirportCode;
	}

	public String getArrAirportCode() {
		return arrAirportCode;
	}

	public void setArrAirportCode(String arrAirportCode) {
		this.arrAirportCode = arrAirportCode;
	}

	public String getDepTime() {
		return depTime;
	}

	public void setDepTime(String depTime) {
		this.depTime = depTime;
	}
	
}

