package com.flight.trs.model.entity;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
//Generated 2016-1-16 17:01:14 by Hibernate Tools 4.3.1.Final

/**
* PassengerGauge generated by hbm2java
*/
@Entity
@Table(name = "TRS_FLIGHT_SEGMENT")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@JsonAutoDetect(fieldVisibility=JsonAutoDetect.Visibility.ANY)
@JsonIgnoreProperties({"serialVersionUID"})
public class Segment 
	implements java.io.Serializable {
	
	/** 
	 * @Fields serialVersionUID : TODO
	 */ 
	private static final long serialVersionUID = 1522556476221715903L;
	
	@JsonUnwrapped
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "carrierCode", column = @Column(name = "CARRIER_CODE", nullable = false, length = 2) ),
			@AttributeOverride(name = "flightNo", column = @Column(name = "FLIGHT_NO", nullable = false, length = 4) ) ,
			@AttributeOverride(name = "depAirportCode", column = @Column(name = "DEP_AIRPORT_CODE", nullable = false, length = 3) ) ,
			@AttributeOverride(name = "arrAirportCode", column = @Column(name = "ARR_AIRPORT_CODE", nullable = false, length = 3) ) ,
			@AttributeOverride(name = "depTime", column = @Column(name = "DEP_TIME", nullable = false, length = 4) ) })
	private SegmentId id;
	
	@ManyToOne
	@JoinColumn(name = "CARRIER_CODE", nullable = false, insertable=false, updatable = false)
	private Carrier carrier;
	
	@ManyToOne
	@JoinColumn(name = "DEP_AIRPORT_CODE", nullable = false, insertable=false, updatable = false)
	private Airport depAirport;
	
	@ManyToOne
	@JoinColumn(name = "ARR_AIRPORT_CODE", nullable = false, insertable=false, updatable = false)
	private Airport arrAirport;
	
	@Column(name = "DEP_TERMINAL", nullable = false, length = 1)
	private String depTerminal;
	
	@Column(name = "ARR_TIME", nullable = false, length = 5)
	private String arrTime;
	
	@Column(name = "ARR_TERMINAL", nullable = false, length = 1)
	private String arrTerminal;
	
	@ManyToOne
	@JoinColumn(name = "AC_CODE", nullable = false)
	private AircraftType aircraftType;
	
	@Column(name = "CL_CODES", nullable = false, length = 3)
	private String clCodes;
	
	@Column(name = "STOPS", nullable = false, length = 10)
	private String stops;
	
	@Column(name = "MEAL_SERVICE", nullable = false, length = 1)
	private String mealService;
	
	@Column(name = "DURATION", nullable = false, length = 4)
	private String duration;
	
	@Column(name = "FLIGHT_SHORT", nullable = false, precision = 5, scale = 1)
	private float flightShort;
	
	@Column(name = "DAYS_OF_OPERATION", nullable = false, length = 7)
	private String daysOfOperation;
	
	@Column(name = "VALIDITY", nullable = false, length = 16)
	private String validity;
	
	@Column(name = "TRA_FLIGHT_NO", length = 4)
	private String traFlightNo;
	
	@ManyToOne
	@JoinColumn(name = "TRA_AIRPORT_CODE")
	private Airport traAirport;
	
	@Column(name = "TRA_ARR_TIME", length = 5)
	private String traArrTime;
	
	@Column(name = "TRA_ARR_TERMINAL", length = 1)
	private String traArrTerminal;
	
	@Column(name = "TRA_DEP_TIME", length = 5)
	private String traDepTime;
	
	@Column(name = "TRA_DEP_TERMINAL", length = 1)
	private String traDepTerminal;
	
	@ManyToOne
	@JoinColumn(name = "TRA_AC_CODE")
	private AircraftType traAircraftType;
	
	@Column(name = "TRA_CL_CODES", length = 3)
	private String traClCodes;
	
	public Segment() {
	}

	
	
	public Segment(SegmentId id, String depTerminal, String arrTime, String arrTerminal, AircraftType aircraftType,
			String clCodes, String stops, String mealService, String duration, float flightShort, String daysOfOperation,
			String validity, String traFlightNo, Airport traAirport, String traArrTime, String traArrTerminal,
			String traDepTime, String traDepTerminal, AircraftType traAircraftType, String traClCodes) {
		super();
		this.id = id;
		this.depTerminal = depTerminal;
		this.arrTime = arrTime;
		this.arrTerminal = arrTerminal;
		this.aircraftType = aircraftType;
		this.clCodes = clCodes;
		this.stops = stops;
		this.mealService = mealService;
		this.duration = duration;
		this.flightShort = flightShort;
		this.daysOfOperation = daysOfOperation;
		this.validity = validity;
		this.traFlightNo = traFlightNo;
		this.traAirport = traAirport;
		this.traArrTime = traArrTime;
		this.traArrTerminal = traArrTerminal;
		this.traDepTime = traDepTime;
		this.traDepTerminal = traDepTerminal;
		this.traAircraftType = traAircraftType;
		this.traClCodes = traClCodes;
	}



	public SegmentId getId() {
		return id;
	}

	public void setId(SegmentId id) {
		this.id = id;
	}

	public Carrier getCarrier() {
		return carrier;
	}

	public void setCarrier(Carrier carrier) {
		this.carrier = carrier;
	}

	public Airport getDepAirport() {
		return depAirport;
	}

	public void setDepAirport(Airport depAirport) {
		this.depAirport = depAirport;
	}

	public Airport getArrAirport() {
		return arrAirport;
	}

	public void setArrAirport(Airport arrAirport) {
		this.arrAirport = arrAirport;
	}

	public String getDepTerminal() {
		return depTerminal;
	}

	public void setDepTerminal(String depTerminal) {
		this.depTerminal = depTerminal;
	}

	public String getArrTime() {
		return arrTime;
	}

	public void setArrTime(String arrTime) {
		this.arrTime = arrTime;
	}

	public String getArrTerminal() {
		return arrTerminal;
	}

	public void setArrTerminal(String arrTerminal) {
		this.arrTerminal = arrTerminal;
	}

	public AircraftType getAircraftType() {
		return aircraftType;
	}

	public void setAircraftType(AircraftType aircraftType) {
		this.aircraftType = aircraftType;
	}

	public String getClCodes() {
		return clCodes;
	}

	public void setClCodes(String clCodes) {
		this.clCodes = clCodes;
	}

	public String getStops() {
		return stops;
	}

	public void setStops(String stops) {
		this.stops = stops;
	}

	public String getMealService() {
		return mealService;
	}

	public void setMealService(String mealService) {
		this.mealService = mealService;
	}

	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public float getFlightShort() {
		return flightShort;
	}

	public void setFlightShort(float flightShort) {
		this.flightShort = flightShort;
	}

	public String getDaysOfOperation() {
		return daysOfOperation;
	}

	public void setDaysOfOperation(String daysOfOperation) {
		this.daysOfOperation = daysOfOperation;
	}

	public String getValidity() {
		return validity;
	}

	public void setValidity(String validity) {
		this.validity = validity;
	}

	public String getTraFlightNo() {
		return traFlightNo;
	}

	public void setTraFlightNo(String traFlightNo) {
		this.traFlightNo = traFlightNo;
	}

	public Airport getTraAirport() {
		return traAirport;
	}

	public void setTraAirport(Airport traAirport) {
		this.traAirport = traAirport;
	}

	public String getTraArrTime() {
		return traArrTime;
	}

	public void setTraArrTime(String traArrTime) {
		this.traArrTime = traArrTime;
	}

	public String getTraArrTerminal() {
		return traArrTerminal;
	}

	public void setTraArrTerminal(String traArrTerminal) {
		this.traArrTerminal = traArrTerminal;
	}

	public String getTraDepTime() {
		return traDepTime;
	}

	public void setTraDepTime(String traDepTime) {
		this.traDepTime = traDepTime;
	}

	public String getTraDepTerminal() {
		return traDepTerminal;
	}

	public void setTraDepTerminal(String traDepTerminal) {
		this.traDepTerminal = traDepTerminal;
	}

	public AircraftType getTraAircraftType() {
		return traAircraftType;
	}

	public void setTraAircraftType(AircraftType traAircraftType) {
		this.traAircraftType = traAircraftType;
	}

	public String getTraClCodes() {
		return traClCodes;
	}

	public void setTraClCodes(String traClCodes) {
		this.traClCodes = traClCodes;
	}
	
}

