package com.flight.trs.model.entity;
// Generated 2016-1-16 17:01:14 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.flight.trs.model.IDeleteNotPhysically;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "TRS_TICKET")
@JsonAutoDetect(getterVisibility=JsonAutoDetect.Visibility.PUBLIC_ONLY)
public class Ticket implements Serializable 
	, IDeleteNotPhysically{

	/** 
	 * @Fields serialVersionUID : TODO
	 */ 
	private static final long serialVersionUID = -812914981504791454L;
	private BigDecimal id;
	private Order order;
	private String ticketNo;
	private String paxName;
	private String paxType;
	private Date paxBirthday;
	private String paxIdType;
	private String paxIdNo;
	private String spaceCode;
	private int ticketFee;
	private short airportTax = 50;
	private short baf = 0;
	private String status = "HK";
	private String remark;
	private Date lastModified;
	private char isLocked = 'u';
	private char isDeleted = 'n';
	
	public Ticket() {
	}

	public Ticket(Order order, String ticketNo, String paxName, String paxType, String paxIdType,
			String paxIdNo, int ticketFee, String status, Date lastModified) {
		this.order = order;
		this.ticketNo = ticketNo;
		this.paxName = paxName;
		this.paxType = paxType;
		this.paxIdType = paxIdType;
		this.paxIdNo = paxIdNo;
		this.ticketFee = ticketFee;
		this.status = status;
		this.lastModified = lastModified;
	}

	public Ticket(Order order, String ticketNo, String paxName, String paxType, Date paxBirthday,
			String paxIdType, String paxIdNo, String spaceCode, int ticketFee, String status, String remark,
			Date lastModified, short airportTax, short baf) {
		this.order = order;
		this.ticketNo = ticketNo;
		this.paxName = paxName;
		this.paxType = paxType;
		this.paxBirthday = paxBirthday;
		this.paxIdType = paxIdType;
		this.paxIdNo = paxIdNo;
		this.spaceCode = spaceCode;
		this.ticketFee = ticketFee;
		this.status = status;
		this.remark = remark;
		this.lastModified = lastModified;
		this.airportTax = airportTax;
		this.baf = baf;
	}

	@Id
	@SequenceGenerator(name = "seqGeneratorTICKET"
		, sequenceName = "SEQ_TICKET"
		, allocationSize=1
		)
	@GeneratedValue(generator = "seqGeneratorTICKET")
	@Column(name = "ID", insertable = false, updatable = false, unique = true
		, nullable = false, precision = 22, scale = 0
		)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_NO", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "TICKET_NO", nullable = true, length = 14)
	public String getTicketNo() {
		return this.ticketNo;
	}

	public void setTicketNo(String ticketNo) {
		this.ticketNo = ticketNo;
	}

	@Column(name = "PAX_NAME", nullable = false, length = 32)
	public String getPaxName() {
		return this.paxName;
	}

	public void setPaxName(String paxName) {
		this.paxName = paxName;
	}

	@Column(name = "PAX_TYPE", nullable = false, length = 24)
	public String getPaxType() {
		return this.paxType;
	}

	public void setPaxType(String paxType) {
		this.paxType = paxType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAX_BIRTHDAY")
	public Date getPaxBirthday() {
		return this.paxBirthday;
	}

	public void setPaxBirthday(Date paxBirthday) {
		this.paxBirthday = paxBirthday;
	}

	@Column(name = "PAX_ID_TYPE", nullable = false, length = 24)
	public String getPaxIdType() {
		return this.paxIdType;
	}

	public void setPaxIdType(String paxIdType) {
		this.paxIdType = paxIdType;
	}

	@Column(name = "PAX_ID_NO", nullable = false, length = 18)
	public String getPaxIdNo() {
		return this.paxIdNo;
	}

	public void setPaxIdNo(String paxIdNo) {
		this.paxIdNo = paxIdNo;
	}

	@Column(name = "SPACE_CODE", length = 3)
	public String getSpaceCode() {
		return this.spaceCode;
	}

	public void setSpaceCode(String spaceCode) {
		this.spaceCode = spaceCode;
	}

	@Column(name = "TICKET_FEE", nullable = false, precision = 6, scale = 0)
	public int getTicketFee() {
		return this.ticketFee;
	}

	public void setTicketFee(int ticketFee) {
		this.ticketFee = ticketFee;
	}

	@Column(name = "AIRPORT_TAX", nullable = false, precision = 4, scale = 0)
	public short getAirportTax() {
		return this.airportTax;
	}

	public void setAirportTax(short airportTax) {
		this.airportTax = airportTax;
	}

	@Column(name = "BAF", nullable = false, precision = 4, scale = 0)
	public short getBaf() {
		return this.baf;
	}

	public void setBaf(short baf) {
		this.baf = baf;
	}
	
	@Column(name = "STATUS", nullable = false, length = 4)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "REMARK", length = 600)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED", nullable = false)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "IS_LOCKED", nullable = false, length = 1)
	public char getIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(char isLocked) {
		this.isLocked = isLocked;
	}

	@Column(name = "IS_DELETED", nullable = false, length = 1)
	public char getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(char isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Transient
	@Override
	public void deleteNotPhysically() {
		// TODO
		setIsDeleted('y');
	}
}
